### PR TITLE
Configurable title attribute

### PR DESCRIPTION
**Pull request by comunidadfusa**
I added an option attribute which can be configured in order to change the title of the locate icon.

### CODE REVIEW

**Comment by domoritz** [comment]
Thanks for the pull request. One last thing before I merge this: Why did you change the indention? Is there a certain code style that one should use or is this just your personal preference? I would happily accept a proper code style but I don't want to change it for no reason.

**Comment by comunidadfusa** [comment]
My mistake! :-P I replaced the whole code instead of adding just the new portions of code. I'll be re-pulling a new version without indention changes, ok?

**Comment by domoritz** [comment]
Great.

**Comment by comunidadfusa** [comment]
I created a new pull request.

**Pull request closed without merging**
