### PR TITLE
Allow to replace loading icon class in options

### PR DESCRIPTION
**Pull request by jtomaszewski**
... for example with `fa fa-spinner`, if someone already has included fontawesome icons in his project.

### CODE REVIEW

**Comment by domoritz** [comment]
Great addition! Can you add this option to the readme as well?

**Comment by domoritz** [comment]
ping :-) @jtomaszewski

**Comment by jtomaszewski** [comment]
Yeah, I'll do it and also some another PRs by the end of this week - stay tuned ;P

**Comment by jtomaszewski** [comment]
I updated the PR with change to README.md . Now you can merge ;)

**Comment by domoritz** [comment]
Can you push your changes?

**Pull request closed without merging**
