### PR TITLE
Created an option to do a marker instead of a circleMarker.

### PR DESCRIPTION
**Pull request by gmccrackin**

### CODE REVIEW

**Comment by domoritz** [comment]
I'll merge as soon as the required refactoring has been done.

**Comment by gmccrackin** [comment]
I totally agree I was thinking that right after I submitted it but I didnt have time to change it. I will try and get to this as soon as possible.

**Comment by gmccrackin** [comment]
I see you haven't merged this. Is there any problems? Do you want me to change anything?

**Comment by domoritz** [comment]
Sorry, I am having a few very busy weeks. I will look at this in a week.

**Pull request merged**
