### PR TITLE
Major refactoring

### LINKED ISSUE #149: Option to move marker for location tracking
I need a map that follows the user's position on the map without panning the map.  I've had good results with custom code that sets the marker lat / lon in `onLocationFound`.

Would a PR for this feature be welcome?  Perhaps a new option such as `keepCurrentMapBounds` that flags whether `drawMarker()` should `panTo` or instead simply move the marker position?

### PR DESCRIPTION
**Pull request by domoritz**
Contains changes from #152

Fixes #149

### CODE REVIEW

**Comment by domoritz** [comment]
@kentr I incorporated your changes and did a major refactoring of the code. Could you play with it and see whether you can find any bugs before I merge it?

**Comment by kentr** [comment]
@domoritz Great.  I'll check it out as soon as I can.

**Comment by domoritz** [comment]
Thanks! I ended up pretty much rewriting the complete logic because it has become too convoluted over the years. Now I feel that I understand it again ;-)

**Comment by kentr** [comment]
@domoritz Looking at this now.

**Comment by domoritz** [comment]
Thanks! I'll test again later as well and merge unless I have to fix something major.

**Comment by kentr** [comment]
@domoritz

The new `setView` behavior appears to be working as expected.

 :+1: for merge.

**Comment by kentr** [comment]
Also psyched that you broke `_onClick()` into a separate function.  I had that in a custom extension and was going to request it as a feature addition.

**Comment by domoritz** [comment]
Great. I couldn't think about the logic any more. Hence the rewrite. I will make one more test pass to test all options and merge then. Thanks for looking over the code!

**Pull request merged**
