### PR TITLE
Leaflet 1.9.2 and minor changes

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
- Tested with Leaflet 1.9.2
- Demo with Leaflet 1.9.2
- Screenshot with default icon
- var -> const, let

### CODE REVIEW

**Comment by domoritz** [comment]
Thank you for the pull request. Please remove the code style changes and submit them as a separate pull request.

**Comment by KristjanESPERANTO** [comment]
OK, I'll do that.

Do you prefer single or double quotes? If you don't have a preference, I would use double quotes as the default.

**Comment by KristjanESPERANTO** [comment]
And do you have an indentation preference? 2 or 4 spaces?

**Comment by KristjanESPERANTO** [comment]
I just undid the code style changes.

**Comment by domoritz** [comment]
Let's use prettier and its defaults.

**Comment by KristjanESPERANTO** [comment]
I like prettier defaults :slightly_smiling_face: 

So #318 is my PR regarding the code style.

**Pull request merged**
