### PR TITLE
Add navigator.compass & deviceOrientation support

### PR DESCRIPTION
**Pull request by jtomaszewski**
This extends a little bit the features of this plugin, but! compass can be easily disabled, so it won't break anything.

Tell me, if you need something more to merge this in.

### CODE REVIEW

**Comment by domoritz** [comment]
This addition is super sweet but I fear that it is outside the scope of what this plugin should do at the moment. It's really cool but most users won't use this feature and it increases the complexity too much. Consequently, I have to reject this pr.

**Comment by jtomaszewski** [comment]
Too bad. I'll have to develop my own fork then =)

**Comment by domoritz** [comment]
Maybe once the rotate marker thing get's merged into leaflet. For now, I think the changes are too larger and it makes the library too hard to modify.

**Comment by marekkalnik** [comment]
Hi,

I think it would be nice to be able to inject features like that in the locatecontrol code. I'll try to make this possible without breaking a lot of code and submit a PR once it's done. I need it for a project of mine anyway and I'm not a big fan of adding conditions for such features.

**Comment by jtomaszewski** [comment]
@marekkalnik , yeah, I'm still for merging it, but it's up to @domoritz.

You can still use my fork if you want to: https://github.com/jtomaszewski/leaflet-locatecontrol/tree/compass .

**Comment by domoritz** [comment]
I'm looking forward to your pr @marekkalnik. It's a great feature but it doesn't necessarily belong into the core so I would love to be able to inject features more efficiently into the locate control.

**Comment by marekkalnik** [comment]
@domoritz what is the browser compatibility your aiming ?

**Comment by domoritz** [comment]
@marekkalnik Everything except IE. For IE best effort but if it doesn't work, it doesn't work.

**Comment by marekkalnik** [comment]
A little update: I have started a big refactoring to understand how the module works : https://github.com/marekkalnik/leaflet-locatecontrol/commit/2ab7d9dbb1750190165663dc54fe7f5b4c53da17

I will now try to extract only the methods that are launched on button press (locate) and those that are managing the display of the pin on map so they can be overriden with L.extend.

The idea is to allow something like this :

``` js
L.Control.Compass = L.Control.Locate.extend({
   execute: function() {
      // execute compass
   };
   display: function() {
     // override to display the arrow
   };
});
```

**Comment by domoritz** [comment]
Sweet, I'm looking forward to your pr.

**Comment by domoritz** [comment]
I am closing this pr in favor of a coming pr by @marekkalnik

**Pull request closed without merging**
